repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: sort-simple-yaml
        files: ^yaml/
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: build_csv_files
        name: build-csv-files
        additional_dependencies:
          - pyaml
          - rich
        entry: ./build_csv_files.py
        language: python
        pass_filenames: false
